server
{
	listen 8080 ;
	server_name example.com;
	error_page 404 /404.html;
	error_page 500 /500.html;
	client_max_body_size 10M;

	location /
	{
		root /var/www/html;
		index index.html;
		autoindex on;
	}

	location /uploads
	{
		upload_store /var/www/uploads;
		upload_pass /upload_handler;
		upload_set_form_field $upload_field_name.name "$upload_file_name";
		upload_set_form_field $upload_field_name.content_type "$upload_content_type";
		upload_set_form_field $upload_field_name.path "$upload_tmp_path";
		upload_pass_form_field "^(.*)$";
	}

	location /cgi-bin
	{
		include cgi.conf;
		fastcgi_param SCRIPT_FILENAME /var/www/cgi-bin$fastcgi_script_name;
		fastcgi_pass unix:/var/run/php-fpm.sock;
		fastcgi_index index.php;
		fastcgi_param PATH_INFO $fastcgi_path_info;
		fastcgi_param SCRIPT_NAME $fastcgi_script_name;
		fastcgi_param QUERY_STRING $query_string;
		fastcgi_param REQUEST_METHOD $request_method;
		fastcgi_param CONTENT_TYPE $content_type;
		fastcgi_param CONTENT_LENGTH $content_length;
	}
}

server
{
	listen 80;
	server_name sub.example.com;
	location /
	{
		root /var/www/sub;
		index index.html;
	}
}
